# src/WM/PlatformBundle/Resources/config/routing.yml

wm_platform_home:
    path:      /{page}
    defaults:
        _controller: WMPlatformBundle:Advert:index
        page:        1
    requirements:
        page: \d*
    
wm_platform_view:
    path:      /advert/{id}
    defaults:
        _controller: WMPlatformBundle:Advert:view
    requirements:
        id: \d+

wm_platform_add:
    path:      /add
    defaults:
        _controller: WMPlatformBundle:Advert:add

wm_platform_edit:
    path:      /edit/{id}
    defaults:
        _controller: WMPlatformBundle:Advert:edit
    requirements:
        id: \d+

wm_platform_delete:
    path:      /delete/{id}
    defaults:
        _controller: WMPlatformBundle:Advert:delete
    requirements:
        id: \d+
